### ISSUE TITLE
SD Image of the Time Server

### ISSUE THREAD

**Issue by izivkov** [izivkov/GShockTimeServer#6]
It would be great if we can create a Pi / Pi-zero SD image with a scripts to setup time. Could be a Python or a Linux Shell scripts. 

The user can simply flash the image to an SD card and boot the Pi, making it into a Time Server.

@harlock974 , do you think you will be interested to work on this?

**Comment by harlock974** [comment]
Yes, I think it will not be that difficult

**Comment by harlock974** [comment]
Suggested procedure :
* installation of minimal Raspbian system on Raspberry
* installation of GshockTimeServer
* activation of user auto connection (with raspi-config)
* add an auto launcher in /home/pi/.profile :

```shell
if (($(ps u|grep -c gshock)==1));then
    python3 path/to/gshock_server.py&
fi
```

**Comment by izivkov** [comment]
Ok, these looks good, but I'm away now, and cannot respond properly. One
thing I like to fix in the current Python code is to enable automatic time
sync , so the watch can sunk by itself. You can take a look at how to
handle this, and I'll respond properly when I get back next week

**Comment by harlock974** [comment]
I am not very comfortable with Python so I prefer you do it.

**Comment by izivkov** [comment]
👍

**Comment by izivkov** [comment]
I'll take care of the Python code. You can  just go ahead and make the SD. We can update the python script later.

Thanks
