### ISSUE TITLE
Installed succesfully, but not sure about connection procedure

### ISSUE THREAD

**Issue by Bashtastic** [izivkov/GShockTimeServer#9]
I have succesfully installed the GShockTimeServer, the script seems to run fine. But how do I pair my watch? Do I need to find the bluetooth address somewhere and insert it manually into the config.ini or do I need to run a other script to pair the watch?

**Comment by izivkov** [comment]
To connect and sync time, just short-press the lower- right button on your
watch. If your watch is set to auto-sync, it will sync up to 4 times daily
without any action on your side.

**Comment by Bashtastic** [comment]
thanks, that clarifies it, I gues I expected some stdout indicating that the sync is happening, successful of not. The sync ends with a 'err' message on mij gab-2100, but maybe the error is more hardware related.

**Comment by izivkov** [comment]
There should be some output to the console. I also hear a beep when
connected. How do you start the script exactly.

If you give me more info on the error, I might be able to help resolve it.

Ivo

**Comment by izivkov** [comment]
You might also be able to set the log level in logger.py. I don't remember
off hand, it might be a parameter setting, but you can hardcore it for
testing.

Ivo

**Comment by Bashtastic** [comment]
Thank you, Ivo. I've determined that the issue lies in the setup of my Raspberry Pi. Additionally, I'm unable to connect to or discover any Bluetooth devices using other Bluetooth commands.
